using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace RepoSkillMiner.Utilities
{
    public static class FileExtensions
    {
        public static XElement GetXml
        {
            get
            {
                return XElement.Parse(@"<ArrayOfTechnologies>
<Technology>
<Name>Documentation</Name>
<Extensions>
<Extension>.pdf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ABAP</Name>
<Extensions>
<Extension>.abap</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ABNF</Name>
<Extensions>
<Extension>.abnf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AMPL</Name>
<Extensions>
<Extension>.ampl</Extension>
<Extension>.mod</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ANTLR</Name>
<Extensions>
<Extension>.g4</Extension>
</Extensions>
</Technology>
<Technology>
<Name>APL</Name>
<Extensions>
<Extension>.apl</Extension>
<Extension>.dyalog</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ASN.1</Name>
<Extensions>
<Extension>.asn</Extension>
<Extension>.asn1</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ASP</Name>
<Extensions>
<Extension>.asp</Extension>
<Extension>.asax</Extension>
<Extension>.ascx</Extension>
<Extension>.ashx</Extension>
<Extension>.asmx</Extension>
<Extension>.aspx</Extension>
<Extension>.axd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ATS</Name>
<Extensions>
<Extension>.dats</Extension>
<Extension>.hats</Extension>
<Extension>.sats</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ActionScript</Name>
<Extensions>
<Extension>.as</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ada</Name>
<Extensions>
<Extension>.adb</Extension>
<Extension>.ada</Extension>
<Extension>.ads</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Agda</Name>
<Extensions>
<Extension>.agda</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Alloy</Name>
<Extensions>
<Extension>.als</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AngelScript</Name>
<Extensions>
<Extension>.as</Extension>
<Extension>.angelscript</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ApacheConf</Name>
<Extensions>
<Extension>.apacheconf</Extension>
<Extension>.vhost</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Apex</Name>
<Extensions>
<Extension>.cls</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AppleScript</Name>
<Extensions>
<Extension>.applescript</Extension>
<Extension>.scpt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Arc</Name>
<Extensions>
<Extension>.arc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AsciiDoc</Name>
<Extensions>
<Extension>.asciidoc</Extension>
<Extension>.adoc</Extension>
<Extension>.asc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AspectJ</Name>
<Extensions>
<Extension>.aj</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Assembly</Name>
<Extensions>
<Extension>.asm</Extension>
<Extension>.a51</Extension>
<Extension>.inc</Extension>
<Extension>.nasm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Asymptote</Name>
<Extensions>
<Extension>.asy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Augeas</Name>
<Extensions>
<Extension>.aug</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AutoHotkey</Name>
<Extensions>
<Extension>.ahk</Extension>
<Extension>.ahkl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AutoIt</Name>
<Extensions>
<Extension>.au3</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Awk</Name>
<Extensions>
<Extension>.awk</Extension>
<Extension>.auk</Extension>
<Extension>.gawk</Extension>
<Extension>.mawk</Extension>
<Extension>.nawk</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ballerina</Name>
<Extensions>
<Extension>.bal</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Batchfile</Name>
<Extensions>
<Extension>.bat</Extension>
<Extension>.cmd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Befunge</Name>
<Extensions>
<Extension>.befunge</Extension>
</Extensions>
</Technology>
<Technology>
<Name>BibTeX</Name>
<Extensions>
<Extension>.bib</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Bison</Name>
<Extensions>
<Extension>.bison</Extension>
</Extensions>
</Technology>
<Technology>
<Name>BitBake</Name>
<Extensions>
<Extension>.bb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Blade</Name>
<Extensions>
<Extension>.blade</Extension>
<Extension>.blade.php</Extension>
</Extensions>
</Technology>
<Technology>
<Name>BlitzBasic</Name>
<Extensions>
<Extension>.bb</Extension>
<Extension>.decls</Extension>
</Extensions>
</Technology>
<Technology>
<Name>BlitzMax</Name>
<Extensions>
<Extension>.bmx</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Bluespec</Name>
<Extensions>
<Extension>.bsv</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Boo</Name>
<Extensions>
<Extension>.boo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Brainfuck</Name>
<Extensions>
<Extension>.b</Extension>
<Extension>.bf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Brightscript</Name>
<Extensions>
<Extension>.brs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>C</Name>
<Extensions>
<Extension>.c</Extension>
<Extension>.cats</Extension>
<Extension>.h</Extension>
<Extension>.idc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CSharp</Name>
<Extensions>
<Extension>.cs</Extension>
<Extension>.cake</Extension>
<Extension>.csx</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CPP</Name>
<Extensions>
<Extension>.cpp</Extension>
<Extension>.cPP</Extension>
<Extension>.cc</Extension>
<Extension>.cp</Extension>
<Extension>.cxx</Extension>
<Extension>.h</Extension>
<Extension>.hPP</Extension>
<Extension>.hh</Extension>
<Extension>.hpp</Extension>
<Extension>.hxx</Extension>
<Extension>.inc</Extension>
<Extension>.inl</Extension>
<Extension>.ino</Extension>
<Extension>.ipp</Extension>
<Extension>.re</Extension>
<Extension>.tcc</Extension>
<Extension>.tpp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>C-ObjDump</Name>
<Extensions>
<Extension>.c-objdump</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CLIPS</Name>
<Extensions>
<Extension>.clp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CMake</Name>
<Extensions>
<Extension>.cmake</Extension>
<Extension>.cmake.in</Extension>
</Extensions>
</Technology>
<Technology>
<Name>COBOL</Name>
<Extensions>
<Extension>.cob</Extension>
<Extension>.cbl</Extension>
<Extension>.ccp</Extension>
<Extension>.cobol</Extension>
<Extension>.cpy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>COLLADA</Name>
<Extensions>
<Extension>.dae</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CSON</Name>
<Extensions>
<Extension>.cson</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CSS</Name>
<Extensions>
<Extension>.css</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CSV</Name>
<Extensions>
<Extension>.csv</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CWeb</Name>
<Extensions>
<Extension>.w</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CartoCSS</Name>
<Extensions>
<Extension>.mss</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ceylon</Name>
<Extensions>
<Extension>.ceylon</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Chapel</Name>
<Extensions>
<Extension>.chpl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Charity</Name>
<Extensions>
<Extension>.ch</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ChucK</Name>
<Extensions>
<Extension>.ck</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cirru</Name>
<Extensions>
<Extension>.cirru</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Clarion</Name>
<Extensions>
<Extension>.clw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Clean</Name>
<Extensions>
<Extension>.icl</Extension>
<Extension>.dcl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Click</Name>
<Extensions>
<Extension>.click</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Clojure</Name>
<Extensions>
<Extension>.clj</Extension>
<Extension>.boot</Extension>
<Extension>.cl2</Extension>
<Extension>.cljc</Extension>
<Extension>.cljs</Extension>
<Extension>.cljs.hl</Extension>
<Extension>.cljscm</Extension>
<Extension>.cljx</Extension>
<Extension>.hic</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CoNLL-U</Name>
<Extensions>
<Extension>.conllu</Extension>
<Extension>.conll</Extension>
</Extensions>
</Technology>
<Technology>
<Name>CoffeeScript</Name>
<Extensions>
<Extension>.coffee</Extension>
<Extension>._coffee</Extension>
<Extension>.cake</Extension>
<Extension>.cjsx</Extension>
<Extension>.iced</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ColdFusion</Name>
<Extensions>
<Extension>.cfm</Extension>
<Extension>.cfml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cool</Name>
<Extensions>
<Extension>.cl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Coq</Name>
<Extensions>
<Extension>.coq</Extension>
<Extension>.v</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cpp-ObjDump</Name>
<Extensions>
<Extension>.cppobjdump</Extension>
<Extension>.cPP-objdump</Extension>
<Extension>.cPPobjdump</Extension>
<Extension>.cpp-objdump</Extension>
<Extension>.cxx-objdump</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Creole</Name>
<Extensions>
<Extension>.creole</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Crystal</Name>
<Extensions>
<Extension>.cr</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Csound</Name>
<Extensions>
<Extension>.orc</Extension>
<Extension>.udo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cuda</Name>
<Extensions>
<Extension>.cu</Extension>
<Extension>.cuh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cycript</Name>
<Extensions>
<Extension>.cy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cython</Name>
<Extensions>
<Extension>.pyx</Extension>
<Extension>.pxd</Extension>
<Extension>.pxi</Extension>
</Extensions>
</Technology>
<Technology>
<Name>D</Name>
<Extensions>
<Extension>.d</Extension>
<Extension>.di</Extension>
</Extensions>
</Technology>
<Technology>
<Name>D-ObjDump</Name>
<Extensions>
<Extension>.d-objdump</Extension>
</Extensions>
</Technology>
<Technology>
<Name>DM</Name>
<Extensions>
<Extension>.dm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>DTrace</Name>
<Extensions>
<Extension>.d</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Dart</Name>
<Extensions>
<Extension>.dart</Extension>
</Extensions>
</Technology>
<Technology>
<Name>DataWeave</Name>
<Extensions>
<Extension>.dwl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Dhall</Name>
<Extensions>
<Extension>.dhall</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Diff</Name>
<Extensions>
<Extension>.diff</Extension>
<Extension>.patch</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Dockerfile</Name>
<Extensions>
<Extension>.dockerfile</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Dogescript</Name>
<Extensions>
<Extension>.djs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Dylan</Name>
<Extensions>
<Extension>.dylan</Extension>
<Extension>.dyl</Extension>
<Extension>.intr</Extension>
<Extension>.lid</Extension>
</Extensions>
</Technology>
<Technology>
<Name>E</Name>
<Extensions>
<Extension>.E</Extension>
</Extensions>
</Technology>
<Technology>
<Name>EBNF</Name>
<Extensions>
<Extension>.ebnf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ECL</Name>
<Extensions>
<Extension>.ecl</Extension>
<Extension>.eclxml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ECLiPSe</Name>
<Extensions>
<Extension>.ecl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>EJS</Name>
<Extensions>
<Extension>.ejs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>EML</Name>
<Extensions>
<Extension>.eml</Extension>
<Extension>.mbox</Extension>
</Extensions>
</Technology>
<Technology>
<Name>EQ</Name>
<Extensions>
<Extension>.eq</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Eagle</Name>
<Extensions>
<Extension>.sch</Extension>
<Extension>.brd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Easybuild</Name>
<Extensions>
<Extension>.eb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>EditorConfig</Name>
<Extensions />
</Technology>
<Technology>
<Name>Eiffel</Name>
<Extensions>
<Extension>.e</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Elixir</Name>
<Extensions>
<Extension>.ex</Extension>
<Extension>.exs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Elm</Name>
<Extensions>
<Extension>.elm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>EmberScript</Name>
<Extensions>
<Extension>.em</Extension>
<Extension>.emberscript</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Erlang</Name>
<Extensions>
<Extension>.erl</Extension>
<Extension>.app.src</Extension>
<Extension>.es</Extension>
<Extension>.escript</Extension>
<Extension>.hrl</Extension>
<Extension>.xrl</Extension>
<Extension>.yrl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>FSharp</Name>
<Extensions>
<Extension>.fs</Extension>
<Extension>.fsi</Extension>
<Extension>.fsx</Extension>
</Extensions>
</Technology>
<Technology>
<Name>FStar</Name>
<Extensions>
<Extension>.fst</Extension>
</Extensions>
</Technology>
<Technology>
<Name>FLUX</Name>
<Extensions>
<Extension>.fx</Extension>
<Extension>.flux</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Factor</Name>
<Extensions>
<Extension>.factor</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Fancy</Name>
<Extensions>
<Extension>.fy</Extension>
<Extension>.fancypack</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Fantom</Name>
<Extensions>
<Extension>.fan</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Filterscript</Name>
<Extensions>
<Extension>.fs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Formatted</Name>
<Extensions>
<Extension>.for</Extension>
<Extension>.eam.fs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Forth</Name>
<Extensions>
<Extension>.fth</Extension>
<Extension>.4th</Extension>
<Extension>.f</Extension>
<Extension>.for</Extension>
<Extension>.forth</Extension>
<Extension>.fr</Extension>
<Extension>.frt</Extension>
<Extension>.fs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Fortran</Name>
<Extensions>
<Extension>.f90</Extension>
<Extension>.f</Extension>
<Extension>.f03</Extension>
<Extension>.f08</Extension>
<Extension>.f77</Extension>
<Extension>.f95</Extension>
<Extension>.for</Extension>
<Extension>.fpp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>FreeMarker</Name>
<Extensions>
<Extension>.ftl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Frege</Name>
<Extensions>
<Extension>.fr</Extension>
</Extensions>
</Technology>
<Technology>
<Name>G-code</Name>
<Extensions>
<Extension>.g</Extension>
<Extension>.cnc</Extension>
<Extension>.gco</Extension>
<Extension>.gcode</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GAML</Name>
<Extensions>
<Extension>.gaml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GAMS</Name>
<Extensions>
<Extension>.gms</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GAP</Name>
<Extensions>
<Extension>.g</Extension>
<Extension>.gap</Extension>
<Extension>.gd</Extension>
<Extension>.gi</Extension>
<Extension>.tst</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GDB</Name>
<Extensions>
<Extension>.gdb</Extension>
<Extension>.gdbinit</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GDScript</Name>
<Extensions>
<Extension>.gd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GLSL</Name>
<Extensions>
<Extension>.glsl</Extension>
<Extension>.fp</Extension>
<Extension>.frag</Extension>
<Extension>.frg</Extension>
<Extension>.fs</Extension>
<Extension>.fsh</Extension>
<Extension>.fshader</Extension>
<Extension>.geo</Extension>
<Extension>.geom</Extension>
<Extension>.glslv</Extension>
<Extension>.gshader</Extension>
<Extension>.shader</Extension>
<Extension>.tesc</Extension>
<Extension>.tese</Extension>
<Extension>.vert</Extension>
<Extension>.vrx</Extension>
<Extension>.vsh</Extension>
<Extension>.vshader</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GN</Name>
<Extensions>
<Extension>.gn</Extension>
<Extension>.gni</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Genie</Name>
<Extensions>
<Extension>.gs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Genshi</Name>
<Extensions>
<Extension>.kid</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gherkin</Name>
<Extensions>
<Extension>.feature</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Glyph</Name>
<Extensions>
<Extension>.glf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gnuplot</Name>
<Extensions>
<Extension>.gp</Extension>
<Extension>.gnu</Extension>
<Extension>.gnuplot</Extension>
<Extension>.p</Extension>
<Extension>.plot</Extension>
<Extension>.plt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Go</Name>
<Extensions>
<Extension>.go</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Golo</Name>
<Extensions>
<Extension>.golo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gosu</Name>
<Extensions>
<Extension>.gs</Extension>
<Extension>.gst</Extension>
<Extension>.gsx</Extension>
<Extension>.vark</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Grace</Name>
<Extensions>
<Extension>.grace</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gradle</Name>
<Extensions>
<Extension>.gradle</Extension>
</Extensions>
</Technology>
<Technology>
<Name>GraphQL</Name>
<Extensions>
<Extension>.graphql</Extension>
<Extension>.gql</Extension>
<Extension>.graphqls</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Groovy</Name>
<Extensions>
<Extension>.groovy</Extension>
<Extension>.grt</Extension>
<Extension>.gtpl</Extension>
<Extension>.gvy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HAProxy</Name>
<Extensions>
<Extension>.cfg</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HCL</Name>
<Extensions>
<Extension>.hcl</Extension>
<Extension>.tf</Extension>
<Extension>.tfvars</Extension>
<Extension>.workflow</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HLSL</Name>
<Extensions>
<Extension>.hlsl</Extension>
<Extension>.cginc</Extension>
<Extension>.fx</Extension>
<Extension>.fxh</Extension>
<Extension>.hlsli</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HTML</Name>
<Extensions>
<Extension>.html</Extension>
<Extension>.htm</Extension>
<Extension>.html.hl</Extension>
<Extension>.inc</Extension>
<Extension>.st</Extension>
<Extension>.xht</Extension>
<Extension>.xhtml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HTMLplusDjango</Name>
<Extensions>
<Extension>.jinja</Extension>
<Extension>.jinja2</Extension>
<Extension>.mustache</Extension>
<Extension>.njk</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HTMLplusECR</Name>
<Extensions>
<Extension>.ecr</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HTMLplusEEX</Name>
<Extensions>
<Extension>.eex</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HTMLplusERB</Name>
<Extensions>
<Extension>.erb</Extension>
<Extension>.erb.deface</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HTMLplusPHP</Name>
<Extensions>
<Extension>.phtml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ASPnetMVC</Name>
<Extensions>
<Extension>.cshtml</Extension>
<Extension>.razor</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HTTP</Name>
<Extensions>
<Extension>.http</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HXML</Name>
<Extensions>
<Extension>.hxml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Hack</Name>
<Extensions>
<Extension>.hack</Extension>
<Extension>.hh</Extension>
<Extension>.hhi</Extension>
<Extension>.php</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Haml</Name>
<Extensions>
<Extension>.haml</Extension>
<Extension>.haml.deface</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Handlebars</Name>
<Extensions>
<Extension>.handlebars</Extension>
<Extension>.hbs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Harbour</Name>
<Extensions>
<Extension>.hb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Haskell</Name>
<Extensions>
<Extension>.hs</Extension>
<Extension>.hs-boot</Extension>
<Extension>.hsc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Haxe</Name>
<Extensions>
<Extension>.hx</Extension>
<Extension>.hxsl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HiveQL</Name>
<Extensions>
<Extension>.q</Extension>
<Extension>.hql</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HolyC</Name>
<Extensions>
<Extension>.hc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Hy</Name>
<Extensions>
<Extension>.hy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>HyPhy</Name>
<Extensions>
<Extension>.bf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>IDL</Name>
<Extensions>
<!--<Extension>.pro</Extension>-->
<Extension>.dlm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>INI</Name>
<Extensions>
<Extension>.ini</Extension>
<Extension>.cfg</Extension>
<Extension>.lektorproject</Extension>
<Extension>.prefs</Extension>
<!--<Extension>.pro</Extension>-->
<!--<Extension>.properties</Extension>-->
</Extensions>
</Technology>
<Technology>
<Name>Idris</Name>
<Extensions>
<Extension>.idr</Extension>
<Extension>.lidr</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Io</Name>
<Extensions>
<Extension>.io</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ioke</Name>
<Extensions>
<Extension>.ik</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Isabelle</Name>
<Extensions>
<Extension>.thy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>J</Name>
<Extensions>
<Extension>.ijs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JFlex</Name>
<Extensions>
<Extension>.flex</Extension>
<Extension>.jflex</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JSON</Name>
<Extensions>
<Extension>.json</Extension>
<Extension>.avsc</Extension>
<Extension>.geojson</Extension>
<Extension>.gltf</Extension>
<Extension>.har</Extension>
<Extension>.ice</Extension>
<Extension>.JSON-tmLanguage</Extension>
<Extension>.jsonl</Extension>
<Extension>.mcmeta</Extension>
<Extension>.tfstate</Extension>
<Extension>.tfstate.backup</Extension>
<Extension>.topojson</Extension>
<Extension>.webapp</Extension>
<Extension>.webmanifest</Extension>
<Extension>.yy</Extension>
<Extension>.yyp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JSON5</Name>
<Extensions>
<Extension>.json5</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JSONLD</Name>
<Extensions>
<Extension>.jsonld</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JSONiq</Name>
<Extensions>
<Extension>.jq</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JSX</Name>
<Extensions>
<Extension>.jsx</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Jasmin</Name>
<Extensions>
<Extension>.j</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Java</Name>
<Extensions>
<Extension>.java</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JavaScript</Name>
<Extensions>
<Extension>.js</Extension>
<Extension>._js</Extension>
<Extension>.bones</Extension>
<Extension>.cjs</Extension>
<Extension>.es</Extension>
<Extension>.es6</Extension>
<Extension>.frag</Extension>
<Extension>.gs</Extension>
<Extension>.jake</Extension>
<Extension>.jsb</Extension>
<Extension>.jscad</Extension>
<Extension>.jsfl</Extension>
<Extension>.jsm</Extension>
<Extension>.jss</Extension>
<Extension>.mjs</Extension>
<Extension>.njs</Extension>
<Extension>.pac</Extension>
<Extension>.sjs</Extension>
<Extension>.ssjs</Extension>
<Extension>.xsjs</Extension>
<Extension>.xsjslib</Extension>
</Extensions>
</Technology>
<Technology>
<Name>JavaScriptplusERB</Name>
<Extensions>
<Extension>.js.erb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Jison</Name>
<Extensions>
<Extension>.jison</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Jolie</Name>
<Extensions>
<Extension>.ol</Extension>
<Extension>.iol</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Jsonnet</Name>
<Extensions>
<Extension>.jsonnet</Extension>
<Extension>.libsonnet</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Julia</Name>
<Extensions>
<Extension>.jl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>KRL</Name>
<Extensions>
<Extension>.krl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Kit</Name>
<Extensions>
<Extension>.kit</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Kotlin</Name>
<Extensions>
<Extension>.kt</Extension>
<Extension>.ktm</Extension>
<Extension>.kts</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LFE</Name>
<Extensions>
<Extension>.lfe</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LLVM</Name>
<Extensions>
<Extension>.ll</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LOLCODE</Name>
<Extensions>
<Extension>.lol</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LSL</Name>
<Extensions>
<Extension>.lsl</Extension>
<Extension>.lslp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LabVIEW</Name>
<Extensions>
<Extension>.lvproj</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Lasso</Name>
<Extensions>
<Extension>.lasso</Extension>
<Extension>.las</Extension>
<Extension>.lasso8</Extension>
<Extension>.lasso9</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Latte</Name>
<Extensions>
<Extension>.latte</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Lean</Name>
<Extensions>
<Extension>.lean</Extension>
<Extension>.hlean</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Less</Name>
<Extensions>
<Extension>.less</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Lex</Name>
<Extensions>
<Extension>.l</Extension>
<Extension>.lex</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LilyPond</Name>
<Extensions>
<Extension>.ly</Extension>
<Extension>.ily</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Limbo</Name>
<Extensions>
<Extension>.b</Extension>
<Extension>.m</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Liquid</Name>
<Extensions>
<Extension>.liquid</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LiveScript</Name>
<Extensions>
<Extension>.ls</Extension>
<Extension>._ls</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Logos</Name>
<Extensions>
<Extension>.xm</Extension>
<Extension>.x</Extension>
<Extension>.xi</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Logtalk</Name>
<Extensions>
<Extension>.lgt</Extension>
<Extension>.logtalk</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LookML</Name>
<Extensions>
<Extension>.lookml</Extension>
<Extension>.model.lkml</Extension>
<Extension>.view.lkml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LoomScript</Name>
<Extensions>
<Extension>.ls</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Lua</Name>
<Extensions>
<Extension>.lua</Extension>
<Extension>.fcgi</Extension>
<Extension>.nse</Extension>
<Extension>.p8</Extension>
<Extension>.pd_lua</Extension>
<Extension>.rbxs</Extension>
<Extension>.wlua</Extension>
</Extensions>
</Technology>
<Technology>
<Name>M</Name>
<Extensions>
<Extension>.mumps</Extension>
<Extension>.m</Extension>
</Extensions>
</Technology>
<Technology>
<Name>M4</Name>
<Extensions>
<Extension>.m4</Extension>
</Extensions>
</Technology>
<Technology>
<Name>M4Sugar</Name>
<Extensions>
<Extension>.m4</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MATLAB</Name>
<Extensions>
<Extension>.matlab</Extension>
<Extension>.m</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MAXScript</Name>
<Extensions>
<Extension>.ms</Extension>
<Extension>.mcr</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MLIR</Name>
<Extensions>
<Extension>.mlir</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MQL4</Name>
<Extensions>
<Extension>.mq4</Extension>
<Extension>.mqh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MQL5</Name>
<Extensions>
<Extension>.mq5</Extension>
<Extension>.mqh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MTML</Name>
<Extensions>
<Extension>.mtml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MUF</Name>
<Extensions>
<Extension>.muf</Extension>
<Extension>.m</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Makefile</Name>
<Extensions>
<Extension>.mak</Extension>
<Extension>.d</Extension>
<Extension>.make</Extension>
<Extension>.mk</Extension>
<Extension>.mkfile</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Mako</Name>
<Extensions>
<Extension>.mako</Extension>
<Extension>.mao</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Markdown</Name>
<Extensions>
<Extension>.md</Extension>
<Extension>.markdown</Extension>
<Extension>.mdown</Extension>
<Extension>.mdwn</Extension>
<Extension>.mdx</Extension>
<Extension>.mkd</Extension>
<Extension>.mkdn</Extension>
<Extension>.mkdown</Extension>
<Extension>.ronn</Extension>
<Extension>.workbook</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Marko</Name>
<Extensions>
<Extension>.marko</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Mask</Name>
<Extensions>
<Extension>.mask</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Mathematica</Name>
<Extensions>
<Extension>.mathematica</Extension>
<Extension>.cdf</Extension>
<Extension>.m</Extension>
<Extension>.ma</Extension>
<Extension>.mt</Extension>
<Extension>.nb</Extension>
<Extension>.nbp</Extension>
<Extension>.wl</Extension>
<Extension>.wlt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Max</Name>
<Extensions>
<Extension>.maxpat</Extension>
<Extension>.maxhelp</Extension>
<Extension>.maxproj</Extension>
<Extension>.mxt</Extension>
<Extension>.pat</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MediaWiki</Name>
<Extensions>
<Extension>.mediawiki</Extension>
<Extension>.wiki</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Mercury</Name>
<Extensions>
<Extension>.m</Extension>
<Extension>.moo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Meson</Name>
<Extensions />
</Technology>
<Technology>
<Name>Metal</Name>
<Extensions>
<Extension>.metal</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MiniD</Name>
<Extensions>
<Extension>.minid</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Mirah</Name>
<Extensions>
<Extension>.druby</Extension>
<Extension>.duby</Extension>
<Extension>.mirah</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Modelica</Name>
<Extensions>
<Extension>.mo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Modula-2</Name>
<Extensions>
<Extension>.mod</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Modula-3</Name>
<Extensions>
<Extension>.i3</Extension>
<Extension>.ig</Extension>
<Extension>.m3</Extension>
<Extension>.mg</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Monkey</Name>
<Extensions>
<Extension>.monkey</Extension>
<Extension>.monkey2</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Moocode</Name>
<Extensions>
<Extension>.moo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>MoonScript</Name>
<Extensions>
<Extension>.moon</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Muse</Name>
<Extensions>
<Extension>.muse</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Myghty</Name>
<Extensions>
<Extension>.myt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NCL</Name>
<Extensions>
<Extension>.ncl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NL</Name>
<Extensions>
<Extension>.nl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NSIS</Name>
<Extensions>
<Extension>.nsi</Extension>
<Extension>.nsh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nearley</Name>
<Extensions>
<Extension>.ne</Extension>
<Extension>.nearley</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nemerle</Name>
<Extensions>
<Extension>.n</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NetLinx</Name>
<Extensions>
<Extension>.axs</Extension>
<Extension>.axi</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NetLinxplusERB</Name>
<Extensions>
<Extension>.axs.erb</Extension>
<Extension>.axi.erb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NetLogo</Name>
<Extensions>
<Extension>.nlogo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NewLisp</Name>
<Extensions>
<Extension>.nl</Extension>
<Extension>.lisp</Extension>
<Extension>.lsp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nextflow</Name>
<Extensions>
<Extension>.nf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nginx</Name>
<Extensions>
<Extension>.nginxconf</Extension>
<Extension>.vhost</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nim</Name>
<Extensions>
<Extension>.nim</Extension>
<Extension>.nim.cfg</Extension>
<Extension>.nimble</Extension>
<Extension>.nimrod</Extension>
<Extension>.nims</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ninja</Name>
<Extensions>
<Extension>.ninja</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nit</Name>
<Extensions>
<Extension>.nit</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nix</Name>
<Extensions>
<Extension>.nix</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Nu</Name>
<Extensions>
<Extension>.nu</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NumPy</Name>
<Extensions>
<Extension>.numpy</Extension>
<Extension>.numpyw</Extension>
<Extension>.numsc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>OCaml</Name>
<Extensions>
<Extension>.ml</Extension>
<Extension>.eliom</Extension>
<Extension>.eliomi</Extension>
<Extension>.ml4</Extension>
<Extension>.mli</Extension>
<Extension>.mll</Extension>
<Extension>.mly</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ObjDump</Name>
<Extensions>
<Extension>.objdump</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ObjectScript</Name>
<Extensions>
<Extension>.cls</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Objective-C</Name>
<Extensions>
<Extension>.m</Extension>
<Extension>.h</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Objective-CPP</Name>
<Extensions>
<Extension>.mm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Objective-J</Name>
<Extensions>
<Extension>.j</Extension>
<Extension>.sj</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Omgrofl</Name>
<Extensions>
<Extension>.omgrofl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Opa</Name>
<Extensions>
<Extension>.opa</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Opal</Name>
<Extensions>
<Extension>.opal</Extension>
</Extensions>
</Technology>
<Technology>
<Name>OpenCL</Name>
<Extensions>
<Extension>.cl</Extension>
<Extension>.opencl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>OpenSCAD</Name>
<Extensions>
<Extension>.scad</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Org</Name>
<Extensions>
<Extension>.org</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ox</Name>
<Extensions>
<Extension>.ox</Extension>
<Extension>.oxh</Extension>
<Extension>.oxo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Oxygene</Name>
<Extensions>
<Extension>.oxygene</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Oz</Name>
<Extensions>
<Extension>.oz</Extension>
</Extensions>
</Technology>
<Technology>
<Name>P4</Name>
<Extensions>
<Extension>.p4</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PHP</Name>
<Extensions>
<Extension>.php</Extension>
<Extension>.aw</Extension>
<Extension>.ctp</Extension>
<Extension>.fcgi</Extension>
<Extension>.inc</Extension>
<Extension>.php3</Extension>
<Extension>.php4</Extension>
<Extension>.php5</Extension>
<Extension>.phps</Extension>
<Extension>.phpt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PLSQL</Name>
<Extensions>
<Extension>.pls</Extension>
<Extension>.bdy</Extension>
<Extension>.ddl</Extension>
<Extension>.fnc</Extension>
<Extension>.pck</Extension>
<Extension>.pkb</Extension>
<Extension>.pks</Extension>
<Extension>.plb</Extension>
<Extension>.plsql</Extension>
<Extension>.prc</Extension>
<Extension>.spc</Extension>
<!--<Extension>.sql</Extension>-->
<Extension>.tpb</Extension>
<Extension>.tps</Extension>
<Extension>.trg</Extension>
<Extension>.vw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PLpgSQL</Name>
<Extensions>
<Extension>.pgsql</Extension>
<!--<Extension>.sql</Extension>-->
</Extensions>
</Technology>
<Technology>
<Name>Pan</Name>
<Extensions>
<Extension>.pan</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Papyrus</Name>
<Extensions>
<Extension>.psc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Parrot</Name>
<Extensions>
<Extension>.parrot</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pascal</Name>
<Extensions>
<Extension>.pas</Extension>
<Extension>.dfm</Extension>
<Extension>.dpr</Extension>
<Extension>.inc</Extension>
<Extension>.lpr</Extension>
<Extension>.pascal</Extension>
<Extension>.pp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pawn</Name>
<Extensions>
<Extension>.pwn</Extension>
<Extension>.inc</Extension>
<Extension>.sma</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pep8</Name>
<Extensions>
<Extension>.pep</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Perl</Name>
<Extensions>
<Extension>.pl</Extension>
<Extension>.al</Extension>
<Extension>.cgi</Extension>
<Extension>.fcgi</Extension>
<Extension>.perl</Extension>
<Extension>.ph</Extension>
<Extension>.plx</Extension>
<Extension>.pm</Extension>
<Extension>.psgi</Extension>
<Extension>.t</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pic</Name>
<Extensions>
<Extension>.pic</Extension>
<Extension>.chem</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pickle</Name>
<Extensions>
<Extension>.pkl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PicoLisp</Name>
<Extensions>
<Extension>.l</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PigLatin</Name>
<Extensions>
<Extension>.pig</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pike</Name>
<Extensions>
<Extension>.pike</Extension>
<Extension>.pmod</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pod</Name>
<Extensions>
<Extension>.pod</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PogoScript</Name>
<Extensions>
<Extension>.pogo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pony</Name>
<Extensions>
<Extension>.pony</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PostCSS</Name>
<Extensions>
<Extension>.pcss</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PostScript</Name>
<Extensions>
<Extension>.ps</Extension>
<Extension>.eps</Extension>
<Extension>.pfa</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PowerBuilder</Name>
<Extensions>
<Extension>.pbt</Extension>
<Extension>.sra</Extension>
<Extension>.sru</Extension>
<Extension>.srw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PowerShell</Name>
<Extensions>
<Extension>.ps1</Extension>
<Extension>.psd1</Extension>
<Extension>.psm1</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Prisma</Name>
<Extensions>
<Extension>.prisma</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Processing</Name>
<Extensions>
<Extension>.pde</Extension>
</Extensions>
</Technology>
<!--<Technology>
<Name>Proguard</Name>
<Extensions>
<Extension>.pro</Extension>
</Extensions>
</Technology>-->
<Technology>
<Name>Prolog</Name>
<Extensions>
<Extension>.pl</Extension>
<Extension>.pro</Extension>
<Extension>.prolog</Extension>
<Extension>.yap</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pug</Name>
<Extensions>
<Extension>.jade</Extension>
<Extension>.pug</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Puppet</Name>
<Extensions>
<Extension>.pp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PureBasic</Name>
<Extensions>
<Extension>.pb</Extension>
<Extension>.pbi</Extension>
</Extensions>
</Technology>
<Technology>
<Name>PureScript</Name>
<Extensions>
<Extension>.purs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Python</Name>
<Extensions>
<Extension>.py</Extension>
<Extension>.bzl</Extension>
<Extension>.cgi</Extension>
<Extension>.fcgi</Extension>
<Extension>.gyp</Extension>
<Extension>.gypi</Extension>
<Extension>.lmi</Extension>
<Extension>.py3</Extension>
<Extension>.pyde</Extension>
<Extension>.pyi</Extension>
<Extension>.pyp</Extension>
<Extension>.pyt</Extension>
<Extension>.pyw</Extension>
<Extension>.rpy</Extension>
<Extension>.spec</Extension>
<Extension>.tac</Extension>
<Extension>.wsgi</Extension>
<Extension>.xpy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>QML</Name>
<Extensions>
<Extension>.qml</Extension>
<Extension>.qbs</Extension>
</Extensions>
</Technology>
<!--<Technology>
<Name>QMake</Name>
<Extensions>
<Extension>.pro</Extension>
<Extension>.pri</Extension>
</Extensions>
</Technology>-->
<Technology>
<Name>Quake</Name>
<Extensions />
</Technology>
<Technology>
<Name>R</Name>
<Extensions>
<Extension>.r</Extension>
<Extension>.rd</Extension>
<Extension>.rsx</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RAML</Name>
<Extensions>
<Extension>.raml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RDoc</Name>
<Extensions>
<Extension>.rdoc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>REALbasic</Name>
<Extensions>
<Extension>.rbbas</Extension>
<Extension>.rbfrm</Extension>
<Extension>.rbmnu</Extension>
<Extension>.rbres</Extension>
<Extension>.rbtbar</Extension>
<Extension>.rbuistate</Extension>
</Extensions>
</Technology>
<Technology>
<Name>REXX</Name>
<Extensions>
<Extension>.rexx</Extension>
<Extension>.pprx</Extension>
<Extension>.rex</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RHTML</Name>
<Extensions>
<Extension>.rhtml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RMarkdown</Name>
<Extensions>
<Extension>.rmd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RPC</Name>
<Extensions>
<Extension>.x</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RUNOFF</Name>
<Extensions>
<Extension>.rnh</Extension>
<Extension>.rno</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Racket</Name>
<Extensions>
<Extension>.rkt</Extension>
<Extension>.rktd</Extension>
<Extension>.rktl</Extension>
<Extension>.scrbl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ragel</Name>
<Extensions>
<Extension>.rl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Rascal</Name>
<Extensions>
<Extension>.rsc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Reason</Name>
<Extensions>
<Extension>.re</Extension>
<Extension>.rei</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Rebol</Name>
<Extensions>
<Extension>.reb</Extension>
<Extension>.r</Extension>
<Extension>.r2</Extension>
<Extension>.r3</Extension>
<Extension>.rebol</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Red</Name>
<Extensions>
<Extension>.red</Extension>
<Extension>.reds</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Redcode</Name>
<Extensions>
<Extension>.cw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RenPy</Name>
<Extensions>
<Extension>.rpy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RenderScript</Name>
<Extensions>
<Extension>.rs</Extension>
<Extension>.rsh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ring</Name>
<Extensions>
<Extension>.ring</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Riot</Name>
<Extensions>
<Extension>.riot</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RobotFramework</Name>
<Extensions>
<Extension>.robot</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Roff</Name>
<Extensions>
<Extension>.roff</Extension>
<Extension>.1</Extension>
<Extension>.1in</Extension>
<Extension>.1m</Extension>
<Extension>.1x</Extension>
<Extension>.2</Extension>
<Extension>.3</Extension>
<Extension>.3in</Extension>
<Extension>.3m</Extension>
<Extension>.3p</Extension>
<Extension>.3pm</Extension>
<Extension>.3qt</Extension>
<Extension>.3x</Extension>
<Extension>.4</Extension>
<Extension>.5</Extension>
<Extension>.6</Extension>
<Extension>.7</Extension>
<Extension>.8</Extension>
<Extension>.9</Extension>
<Extension>.l</Extension>
<Extension>.man</Extension>
<Extension>.mdoc</Extension>
<Extension>.me</Extension>
<Extension>.ms</Extension>
<Extension>.n</Extension>
<Extension>.nr</Extension>
<Extension>.rno</Extension>
<Extension>.tmac</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Rouge</Name>
<Extensions>
<Extension>.rg</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ruby</Name>
<Extensions>
<Extension>.rb</Extension>
<Extension>.builder</Extension>
<Extension>.eye</Extension>
<Extension>.fcgi</Extension>
<Extension>.gemspec</Extension>
<Extension>.god</Extension>
<Extension>.jbuilder</Extension>
<Extension>.mspec</Extension>
<Extension>.pluginspec</Extension>
<Extension>.podspec</Extension>
<Extension>.rabl</Extension>
<Extension>.rake</Extension>
<Extension>.rbi</Extension>
<Extension>.rbuild</Extension>
<Extension>.rbw</Extension>
<Extension>.rbx</Extension>
<Extension>.ru</Extension>
<Extension>.ruby</Extension>
<Extension>.spec</Extension>
<Extension>.thor</Extension>
<Extension>.watchr</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Rust</Name>
<Extensions>
<Extension>.rs</Extension>
<Extension>.rs.in</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SAS</Name>
<Extensions>
<Extension>.sas</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SCSS</Name>
<Extensions>
<Extension>.scss</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SMT</Name>
<Extensions>
<Extension>.smt2</Extension>
<Extension>.smt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SPARQL</Name>
<Extensions>
<Extension>.sparql</Extension>
<Extension>.rq</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SQF</Name>
<Extensions>
<Extension>.sqf</Extension>
<Extension>.hqf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SQL</Name>
<Extensions>
<Extension>.sql</Extension>
<Extension>.cql</Extension>
<Extension>.ddl</Extension>
<Extension>.inc</Extension>
<Extension>.mysql</Extension>
<Extension>.prc</Extension>
<Extension>.tab</Extension>
<Extension>.udf</Extension>
<Extension>.viw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SQLPL</Name>
<Extensions>
<!--<Extension>.sql</Extension>-->
<Extension>.db2</Extension>
</Extensions>
</Technology>
<Technology>
<Name>STON</Name>
<Extensions>
<Extension>.ston</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SVG</Name>
<Extensions>
<Extension>.svg</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Sage</Name>
<Extensions>
<Extension>.sage</Extension>
<Extension>.sagews</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SaltStack</Name>
<Extensions>
<Extension>.sls</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Sass</Name>
<Extensions>
<Extension>.sass</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Scala</Name>
<Extensions>
<Extension>.scala</Extension>
<Extension>.kojo</Extension>
<Extension>.sbt</Extension>
<Extension>.sc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Scaml</Name>
<Extensions>
<Extension>.scaml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Scheme</Name>
<Extensions>
<Extension>.scm</Extension>
<Extension>.sch</Extension>
<Extension>.sld</Extension>
<Extension>.sls</Extension>
<Extension>.sps</Extension>
<Extension>.ss</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Scilab</Name>
<Extensions>
<Extension>.sci</Extension>
<Extension>.sce</Extension>
<Extension>.tst</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Self</Name>
<Extensions>
<Extension>.self</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ShaderLab</Name>
<Extensions>
<Extension>.shader</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Shell</Name>
<Extensions>
<Extension>.sh</Extension>
<Extension>.bash</Extension>
<Extension>.bats</Extension>
<Extension>.cgi</Extension>
<Extension>.command</Extension>
<Extension>.fcgi</Extension>
<Extension>.ksh</Extension>
<Extension>.sh.in</Extension>
<Extension>.tmux</Extension>
<Extension>.tool</Extension>
<Extension>.zsh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ShellSession</Name>
<Extensions>
<Extension>.sh-session</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Shen</Name>
<Extensions>
<Extension>.shen</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Slash</Name>
<Extensions>
<Extension>.sl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Slice</Name>
<Extensions>
<Extension>.ice</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Slim</Name>
<Extensions>
<Extension>.slim</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SmPL</Name>
<Extensions>
<Extension>.cocci</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Smali</Name>
<Extensions>
<Extension>.smali</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Smalltalk</Name>
<Extensions>
<Extension>.st</Extension>

</Extensions>
</Technology>
<Technology>
<Name>Smarty</Name>
<Extensions>
<Extension>.tpl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Solidity</Name>
<Extensions />
</Technology>
<Technology>
<Name>SourcePawn</Name>
<Extensions>
<Extension>.sp</Extension>
<Extension>.inc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Squirrel</Name>
<Extensions>
<Extension>.nut</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Stan</Name>
<Extensions>
<Extension>.stan</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Stata</Name>
<Extensions>
<Extension>.do</Extension>
<Extension>.ado</Extension>
<Extension>.doh</Extension>
<Extension>.ihlp</Extension>
<Extension>.mata</Extension>
<Extension>.matah</Extension>
<Extension>.sthlp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Stylus</Name>
<Extensions>
<Extension>.styl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SugarSS</Name>
<Extensions>
<Extension>.sss</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SuperCollider</Name>
<Extensions>
<Extension>.sc</Extension>
<Extension>.scd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Svelte</Name>
<Extensions>
<Extension>.svelte</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Swift</Name>
<Extensions>
<Extension>.swift</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SystemVerilog</Name>
<Extensions>
<Extension>.sv</Extension>
<Extension>.svh</Extension>
<Extension>.vh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>TLA</Name>
<Extensions>
<Extension>.tla</Extension>
</Extensions>
</Technology>
<Technology>
<Name>TOML</Name>
<Extensions>
<Extension>.toml</Extension>
</Extensions>
</Technology>
<!--<Technology>
<Name>TSQL</Name>
<Extensions>
<Extension>.sql</Extension>
</Extensions>
</Technology>-->
<Technology>
<Name>TSX</Name>
<Extensions>
<Extension>.tsx</Extension>
</Extensions>
</Technology>
<Technology>
<Name>TXL</Name>
<Extensions>
<Extension>.txl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Tcl</Name>
<Extensions>
<Extension>.tcl</Extension>
<Extension>.adp</Extension>
<Extension>.tm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Tcsh</Name>
<Extensions>
<Extension>.tcsh</Extension>
<Extension>.csh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>TeX</Name>
<Extensions>
<Extension>.tex</Extension>
<Extension>.aux</Extension>
<Extension>.bbx</Extension>
<Extension>.cbx</Extension>
<Extension>.cls</Extension>
<Extension>.dtx</Extension>
<Extension>.ins</Extension>
<Extension>.lbx</Extension>
<Extension>.ltx</Extension>
<Extension>.mkii</Extension>
<Extension>.mkiv</Extension>
<Extension>.mkvi</Extension>
<Extension>.sty</Extension>
<Extension>.toc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Tea</Name>
<Extensions>
<Extension>.tea</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Terra</Name>
<Extensions>
<Extension>.t</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Texinfo</Name>
<Extensions>
<Extension>.texinfo</Extension>
<Extension>.texi</Extension>
<Extension>.txi</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Text</Name>
<Extensions>
<Extension>.txt</Extension>
<Extension>.fr</Extension>
<Extension>.nb</Extension>
<Extension>.ncl</Extension>
<Extension>.no</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Textile</Name>
<Extensions>
<Extension>.textile</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Thrift</Name>
<Extensions>
<Extension>.thrift</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Turing</Name>
<Extensions>
<Extension>.t</Extension>
<Extension>.tu</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Turtle</Name>
<Extensions>
<Extension>.ttl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Twig</Name>
<Extensions>
<Extension>.twig</Extension>
</Extensions>
</Technology>
<Technology>
<Name>TypeScript</Name>
<Extensions>
<Extension>.ts</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Uno</Name>
<Extensions>
<Extension>.uno</Extension>
</Extensions>
</Technology>
<Technology>
<Name>UnrealScript</Name>
<Extensions>
<Extension>.uc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>UrWeb</Name>
<Extensions>
<Extension>.ur</Extension>
<Extension>.urs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>V</Name>
<Extensions>
<Extension>.v</Extension>
</Extensions>
</Technology>
<Technology>
<Name>VBA</Name>
<Extensions>
<Extension>.bas</Extension>
<Extension>.cls</Extension>
<Extension>.frm</Extension>
<Extension>.frx</Extension>
<Extension>.vba</Extension>
</Extensions>
</Technology>
<Technology>
<Name>VBScript</Name>
<Extensions>
<Extension>.vbs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>VCL</Name>
<Extensions>
<Extension>.vcl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>VHDL</Name>
<Extensions>
<Extension>.vhdl</Extension>
<Extension>.vhd</Extension>
<Extension>.vhf</Extension>
<Extension>.vhi</Extension>
<Extension>.vho</Extension>
<Extension>.vhs</Extension>
<Extension>.vht</Extension>
<Extension>.vhw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Vala</Name>
<Extensions>
<Extension>.vala</Extension>
<Extension>.vapi</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Verilog</Name>
<Extensions>
<Extension>.v</Extension>
<Extension>.veo</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Volt</Name>
<Extensions>
<Extension>.volt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Vue</Name>
<Extensions>
<Extension>.vue</Extension>
</Extensions>
</Technology>
<Technology>
<Name>WebAssembly</Name>
<Extensions>
<Extension>.wast</Extension>
<Extension>.wat</Extension>
</Extensions>
</Technology>
<Technology>
<Name>WebIDL</Name>
<Extensions>
<Extension>.webidl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>WebVTT</Name>
<Extensions>
<Extension>.vtt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Wollok</Name>
<Extensions>
<Extension>.wlk</Extension>
</Extensions>
</Technology>
<Technology>
<Name>X10</Name>
<Extensions>
<Extension>.x10</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XC</Name>
<Extensions>
<Extension>.xc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XCompose</Name>
<Extensions />
</Technology>
<Technology>
<Name>XML</Name>
<Extensions>
<Extension>.xml</Extension>
<Extension>.adml</Extension>
<Extension>.admx</Extension>
<Extension>.ant</Extension>
<Extension>.axml</Extension>
<Extension>.builds</Extension>
<Extension>.ccproj</Extension>
<Extension>.ccxml</Extension>
<Extension>.clixml</Extension>
<Extension>.cproject</Extension>
<Extension>.cscfg</Extension>
<Extension>.csdef</Extension>
<Extension>.csl</Extension>
<Extension>.csproj</Extension>
<Extension>.ct</Extension>
<Extension>.depproj</Extension>
<Extension>.dita</Extension>
<Extension>.ditamap</Extension>
<Extension>.ditaval</Extension>
<Extension>.dll.config</Extension>
<Extension>.dotsettings</Extension>
<Extension>.filters</Extension>
<Extension>.fsproj</Extension>
<Extension>.fxml</Extension>
<Extension>.glade</Extension>
<Extension>.gml</Extension>
<Extension>.gmx</Extension>
<Extension>.grxml</Extension>
<Extension>.iml</Extension>
<Extension>.ivy</Extension>
<Extension>.jelly</Extension>
<Extension>.jsproj</Extension>
<Extension>.kml</Extension>
<Extension>.launch</Extension>
<Extension>.mdpolicy</Extension>
<Extension>.mjml</Extension>
<Extension>.mm</Extension>
<Extension>.mod</Extension>
<Extension>.mxml</Extension>
<Extension>.natvis</Extension>
<Extension>.ncl</Extension>
<Extension>.ndproj</Extension>
<Extension>.nproj</Extension>
<Extension>.nuspec</Extension>
<Extension>.odd</Extension>
<Extension>.osm</Extension>
<Extension>.pkgproj</Extension>
<Extension>.pluginspec</Extension>
<Extension>.proj</Extension>
<Extension>.props</Extension>
<Extension>.ps1xml</Extension>
<Extension>.psc1</Extension>
<Extension>.pt</Extension>
<Extension>.rdf</Extension>
<Extension>.resx</Extension>
<Extension>.rss</Extension>
<Extension>.sch</Extension>
<Extension>.scxml</Extension>
<Extension>.sfproj</Extension>
<Extension>.shproj</Extension>
<Extension>.srdf</Extension>
<Extension>.storyboard</Extension>
<Extension>.sublime-snippet</Extension>
<Extension>.targets</Extension>
<Extension>.tml</Extension>
<Extension>.ts</Extension>
<Extension>.tsx</Extension>
<Extension>.ui</Extension>
<Extension>.urdf</Extension>
<Extension>.ux</Extension>
<Extension>.vbproj</Extension>
<Extension>.vcxproj</Extension>
<Extension>.vsixmanifest</Extension>
<Extension>.vssettings</Extension>
<Extension>.vstemplate</Extension>
<Extension>.vxml</Extension>
<Extension>.wixproj</Extension>
<Extension>.workflow</Extension>
<Extension>.wsdl</Extension>
<Extension>.wsf</Extension>
<Extension>.wxi</Extension>
<Extension>.wxl</Extension>
<Extension>.wxs</Extension>
<Extension>.x3d</Extension>
<Extension>.xacro</Extension>

<Extension>.xib</Extension>
<Extension>.xlf</Extension>
<Extension>.xliff</Extension>
<Extension>.xmi</Extension>
<Extension>.xml.dist</Extension>
<Extension>.xproj</Extension>
<Extension>.xsd</Extension>
<Extension>.xspec</Extension>
<Extension>.xul</Extension>
<Extension>.zcml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Xaml</Name>
<Extensions>
<Extension>.xaml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XPages</Name>
<Extensions>
<Extension>.xsp-config</Extension>
<Extension>.xsp.metadata</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XProc</Name>
<Extensions>
<Extension>.xpl</Extension>
<Extension>.xproc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XQuery</Name>
<Extensions>
<Extension>.xquery</Extension>
<Extension>.xq</Extension>
<Extension>.xql</Extension>
<Extension>.xqm</Extension>
<Extension>.xqy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XS</Name>
<Extensions>
<Extension>.xs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XSLT</Name>
<Extensions>
<Extension>.xslt</Extension>
<Extension>.xsl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Xojo</Name>
<Extensions>
<Extension>.xojo_code</Extension>
<Extension>.xojo_menu</Extension>
<Extension>.xojo_report</Extension>
<Extension>.xojo_script</Extension>
<Extension>.xojo_toolbar</Extension>
<Extension>.xojo_window</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Xtend</Name>
<Extensions>
<Extension>.xtend</Extension>
</Extensions>
</Technology>
<Technology>
<Name>YAML</Name>
<Extensions>
<Extension>.yml</Extension>
<Extension>.mir</Extension>
<Extension>.reek</Extension>
<Extension>.rviz</Extension>
<Extension>.sublime-syntax</Extension>
<Extension>.syntax</Extension>
<Extension>.yaml</Extension>
<Extension>.yaml-tmlanguage</Extension>
<Extension>.yaml.sed</Extension>
<Extension>.yml.mysql</Extension>
</Extensions>
</Technology>
<Technology>
<Name>YANG</Name>
<Extensions>
<Extension>.yang</Extension>
</Extensions>
</Technology>
<Technology>
<Name>YARA</Name>
<Extensions>
<Extension>.yar</Extension>
<Extension>.yara</Extension>
</Extensions>
</Technology>
<Technology>
<Name>YASnippet</Name>
<Extensions>
<Extension>.yasnippet</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Yacc</Name>
<Extensions>
<Extension>.y</Extension>
<Extension>.yacc</Extension>
<Extension>.yy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ZAP</Name>
<Extensions>
<Extension>.zap</Extension>
<Extension>.xzap</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ZIL</Name>
<Extensions>
<Extension>.zil</Extension>
<Extension>.mud</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Zeek</Name>
<Extensions>
<Extension>.zeek</Extension>
<Extension>.bro</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ZenScript</Name>
<Extensions>
<Extension>.zs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Zephir</Name>
<Extensions>
<Extension>.zep</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Zig</Name>
<Extensions>
<Extension>.zig</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Zimpl</Name>
<Extensions>
<Extension>.zimpl</Extension>
<Extension>.zmpl</Extension>
<Extension>.zpl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>desktop</Name>
<Extensions>
<Extension>.desktop</Extension>
<Extension>.desktop.in</Extension>
</Extensions>
</Technology>
<Technology>
<Name>dircolors</Name>
<Extensions>
<Extension>.dircolors</Extension>
</Extensions>
</Technology>
<Technology>
<Name>eC</Name>
<Extensions>
<Extension>.ec</Extension>
<Extension>.eh</Extension>
</Extensions>
</Technology>
<Technology>
<Name>edn</Name>
<Extensions>
<Extension>.edn</Extension>
</Extensions>
</Technology>
<Technology>
<Name>fish</Name>
<Extensions>
<Extension>.fish</Extension>
</Extensions>
</Technology>
<Technology>
<Name>mcfunction</Name>
<Extensions>
<Extension>.mcfunction</Extension>
</Extensions>
</Technology>
<Technology>
<Name>mupad</Name>
<Extensions>
<Extension>.mu</Extension>
</Extensions>
</Technology>
<Technology>
<Name>nanorc</Name>
<Extensions>
<Extension>.nanorc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>nesC</Name>
<Extensions>
<Extension>.nc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>ooc</Name>
<Extensions>
<Extension>.ooc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>q</Name>
<Extensions>
<Extension>.q</Extension>
</Extensions>
</Technology>
<Technology>
<Name>reStructuredText</Name>
<Extensions>
<Extension>.rst</Extension>
<Extension>.rest</Extension>
<Extension>.rest.txt</Extension>
<Extension>.rst.txt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>sed</Name>
<Extensions>
<Extension>.sed</Extension>
</Extensions>
</Technology>
<Technology>
<Name>wdl</Name>
<Extensions>
<Extension>.wdl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>wisp</Name>
<Extensions>
<Extension>.wisp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>xBase</Name>
<Extensions>
<Extension>.prg</Extension>
<Extension>.ch</Extension>
<Extension>.prw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>OneC_Enterprise</Name>
<Extensions>
<Extension>.bsl</Extension>
<Extension>.os</Extension>
</Extensions>
</Technology>
<Technology>
<Name>AGS_Script</Name>
<Extensions>
<Extension>.asc</Extension>
<Extension>.ash</Extension>
</Extensions>
</Technology>
<Technology>
<Name>API_Blueprint</Name>
<Extensions>
<Extension>.apib</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Adobe_Font_Metrics</Name>
<Extensions>
<Extension>.afm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Alpine_Abuild</Name>
<Extensions />
</Technology>
<Technology>
<Name>Altium_Designer</Name>
<Extensions>
<Extension>.OutJob</Extension>
<Extension>.PcbDoc</Extension>
<Extension>.PrjPCB</Extension>
<Extension>.SchDoc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ant_Build_System</Name>
<Extensions />
</Technology>
<Technology>
<Name>Apollo_Guidance_Computer</Name>
<Extensions>
<Extension>.agc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>C2hs_Haskell</Name>
<Extensions>
<Extension>.chs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cabal_Config</Name>
<Extensions>
<Extension>.cabal</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Capn_Proto</Name>
<Extensions>
<Extension>.capnp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Closure_Templates</Name>
<Extensions>
<Extension>.soy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Cloud_Firestore_Security_Rules</Name>
<Extensions />
</Technology>
<Technology>
<Name>ColdFusion_CFC</Name>
<Extensions>
<Extension>.cfc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Common_Lisp</Name>
<Extensions>
<Extension>.lisp</Extension>
<Extension>.asd</Extension>
<Extension>.cl</Extension>
<Extension>.l</Extension>
<Extension>.lsp</Extension>
<Extension>.ny</Extension>
<Extension>.podsl</Extension>
<Extension>.sexp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Common_Workflow_Language</Name>
<Extensions>
<Extension>.cwl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Component_Pascal</Name>
<Extensions>
<Extension>.cp</Extension>
<Extension>.cps</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Csound_Document</Name>
<Extensions>
<Extension>.csd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Csound_Score</Name>
<Extensions>
<Extension>.sco</Extension>
</Extensions>
</Technology>
<Technology>
<Name>DIGITAL_Command_Language</Name>
<Extensions>
<Extension>.com</Extension>
</Extensions>
</Technology>
<Technology>
<Name>DNS_Zone</Name>
<Extensions>
<Extension>.zone</Extension>
<Extension>.arpa</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Darcs_Patch</Name>
<Extensions>
<Extension>.darcspatch</Extension>
<Extension>.dpatch</Extension>
</Extensions>
</Technology>
<Technology>
<Name>DirectX_3D_File</Name>
<Extensions>
<Extension>.x</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ecere_Projects</Name>
<Extensions>
<Extension>.epj</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Edje_Data_Collection</Name>
<Extensions>
<Extension>.edc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Emacs_Lisp</Name>
<Extensions>
<Extension>.el</Extension>
<Extension>.emacs</Extension>
<Extension>.emacs.desktop</Extension>
</Extensions>
</Technology>
<Technology>
<Name>FIGlet_Font</Name>
<Extensions>
<Extension>.flf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Filebench_WML</Name>
<Extensions>
<Extension>.f</Extension>
</Extensions>
</Technology>

<Technology>
<Name>Game_Maker_Language</Name>
<Extensions>
<Extension>.gml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gentoo_Ebuild</Name>
<Extensions>
<Extension>.ebuild</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gentoo_Eclass</Name>
<Extensions>
<Extension>.eclass</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gerber_Image</Name>
<Extensions>
<Extension>.gbr</Extension>
<Extension>.gbl</Extension>
<Extension>.gbo</Extension>
<Extension>.gbp</Extension>
<Extension>.gbs</Extension>
<Extension>.gko</Extension>
<Extension>.gml</Extension>
<Extension>.gpb</Extension>
<Extension>.gpt</Extension>
<Extension>.gtl</Extension>
<Extension>.gto</Extension>
<Extension>.gtp</Extension>
<Extension>.gts</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Gettext_Catalog</Name>
<Extensions>
<Extension>.po</Extension>
<Extension>.pot</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Git_Attributes</Name>
<Extensions />
</Technology>
<Technology>
<Name>Git_Config</Name>
<Extensions>
<Extension>.gitconfig</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Glyph_Bitmap_Distribution_Format</Name>
<Extensions>
<Extension>.bdf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Grammatical_Framework</Name>
<Extensions>
<Extension>.gf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Graph_Modeling_Language</Name>
<Extensions>
<Extension>.gml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Graphviz_DOT</Name>
<Extensions>
<Extension>.dot</Extension>
<Extension>.gv</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Groovy_Server_Pages</Name>
<Extensions>
<Extension>.gsp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>IGOR_Pro</Name>
<Extensions>
<Extension>.ipf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>IRC_log</Name>
<Extensions>
<Extension>.irclog</Extension>
<Extension>.weechatlog</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Ignore_List</Name>
<Extensions>
<Extension>.gitignore</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Inform_7</Name>
<Extensions>
<Extension>.ni</Extension>
<Extension>.i7x</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Inno_Setup</Name>
<Extensions>
<Extension>.iss</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Isabelle_ROOT</Name>
<Extensions />
</Technology>
<Technology>
<Name>JSON_with_Comments</Name>
<Extensions>
<Extension>.sublime-build</Extension>
<Extension>.sublime-commands</Extension>
<Extension>.sublime-completions</Extension>
<Extension>.sublime-keymap</Extension>
<Extension>.sublime-macro</Extension>
<Extension>.sublime-menu</Extension>
<Extension>.sublime-mousemap</Extension>
<Extension>.sublime-project</Extension>
<Extension>.sublime-settings</Extension>
<Extension>.sublime-theme</Extension>
<Extension>.sublime-workspace</Extension>
<Extension>.sublime_metrics</Extension>
<Extension>.sublime_session</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Java_Properties</Name>
<Extensions>
<Extension>.properties</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Java_Server_Pages</Name>
<Extensions>
<Extension>.jsp</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Jison_Lex</Name>
<Extensions>
<Extension>.jisonlex</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Jupyter_Notebook</Name>
<Extensions>
<Extension>.ipynb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>KiCad_Layout</Name>
<Extensions>
<Extension>.kicad_pcb</Extension>
<Extension>.kicad_mod</Extension>
<Extension>.kicad_wks</Extension>
</Extensions>
</Technology>
<Technology>
<Name>KiCad_Legacy_Layout</Name>
<Extensions>
<Extension>.brd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>KiCad_Schematic</Name>
<Extensions>
<Extension>.sch</Extension>
</Extensions>
</Technology>
<Technology>
<Name>LTspice_Symbol</Name>
<Extensions>
<Extension>.asy</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Linker_Script</Name>
<Extensions>
<Extension>.ld</Extension>
<Extension>.lds</Extension>
<Extension>.x</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Linux_Kernel_Module</Name>
<Extensions>
<Extension>.mod</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Literate_Agda</Name>
<Extensions>
<Extension>.lagda</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Literate_CoffeeScript</Name>
<Extensions>
<Extension>.litcoffee</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Literate_Haskell</Name>
<Extensions>
<Extension>.lhs</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Maven_POM</Name>
<Extensions />
</Technology>
<Technology>
<Name>Module_Management_System</Name>
<Extensions>
<Extension>.mms</Extension>
<Extension>.mmk</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Motorola_68K_Assembly</Name>
<Extensions>
<Extension>.X68</Extension>
</Extensions>
</Technology>
<Technology>
<Name>NPM_Config</Name>
<Extensions />
</Technology>
<Technology>
<Name>Open_Policy_Agent</Name>
<Extensions>
<Extension>.rego</Extension>
</Extensions>
</Technology>
<Technology>
<Name>OpenEdge_ABL</Name>
<Extensions>
<Extension>.p</Extension>
<Extension>.cls</Extension>
<Extension>.w</Extension>
</Extensions>
</Technology>
<Technology>
<Name>OpenRC_runscript</Name>
<Extensions />
</Technology>
<!--<Technology>
<Name>OpenStep_Property_List</Name>
<Extensions>
<Extension>.plist</Extension>
</Extensions>
</Technology>-->
<Technology>
<Name>OpenType_Feature_File</Name>
<Extensions>
<Extension>.fea</Extension>
</Extensions>
</Technology>
<Technology>
<Name>POV-Ray_SDL</Name>
<Extensions>
<Extension>.pov</Extension>
<Extension>.inc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Parrot_Assembly</Name>
<Extensions>
<Extension>.pasm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Parrot_Internal_Representation</Name>
<Extensions>
<Extension>.pir</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Perl_6</Name>
<Extensions>
<Extension>.6pl</Extension>
<Extension>.6pm</Extension>
<Extension>.nqp</Extension>
<Extension>.p6</Extension>
<Extension>.p6l</Extension>
<Extension>.p6m</Extension>
<Extension>.pl</Extension>
<Extension>.pl6</Extension>
<Extension>.pm</Extension>
<Extension>.pm6</Extension>
<Extension>.t</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pod_6</Name>
<Extensions>
<Extension>.pod</Extension>
<Extension>.pod6</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Propeller_Spin</Name>
<Extensions>
<Extension>.spin</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Protocol_Buffer</Name>
<Extensions>
<Extension>.proto</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Public_Key</Name>
<Extensions>
<Extension>.asc</Extension>
<Extension>.pub</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Pure_Data</Name>
<Extensions>
<Extension>.pd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Python_console</Name>
<Extensions />
</Technology>
<Technology>
<Name>Python_traceback</Name>
<Extensions>
<Extension>.pytb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>RPM_Spec</Name>
<Extensions>
<Extension>.spec</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Raw_token_data</Name>
<Extensions>
<Extension>.raw</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Readline_Config</Name>
<Extensions />
</Technology>
<Technology>
<Name>Regular_Expression</Name>
<Extensions>
<Extension>.regexp</Extension>
<Extension>.regex</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Rich_Text_Format</Name>
<Extensions>
<Extension>.rtf</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Roff_Manpage</Name>
<Extensions>
<Extension>.1</Extension>
<Extension>.1in</Extension>
<Extension>.1m</Extension>
<Extension>.1x</Extension>
<Extension>.2</Extension>
<Extension>.3</Extension>
<Extension>.3in</Extension>
<Extension>.3m</Extension>
<Extension>.3p</Extension>
<Extension>.3pm</Extension>
<Extension>.3qt</Extension>
<Extension>.3x</Extension>
<Extension>.4</Extension>
<Extension>.5</Extension>
<Extension>.6</Extension>
<Extension>.7</Extension>
<Extension>.8</Extension>
<Extension>.9</Extension>
<Extension>.man</Extension>
<Extension>.mdoc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SRecode_Template</Name>
<Extensions>
<Extension>.srt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SSH_Config</Name>
<Extensions />
</Technology>
<Technology>
<Name>Spline_Font_Database</Name>
<Extensions>
<Extension>.sfd</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Standard_ML</Name>
<Extensions>
<Extension>.ML</Extension>
<Extension>.fun</Extension>
<Extension>.sig</Extension>
<Extension>.sml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>SubRip_Text</Name>
<Extensions>
<Extension>.srt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>TI_Program</Name>
<Extensions>
<Extension>.8xp</Extension>
<Extension>.8xk</Extension>
<Extension>.8xk.txt</Extension>
<Extension>.8xp.txt</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Type_Language</Name>
<Extensions>
<Extension>.tl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Unified_Parallel_C</Name>
<Extensions>
<Extension>.upc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Unity3D_Asset</Name>
<Extensions>
<Extension>.anim</Extension>
<Extension>.asset</Extension>
<Extension>.mask</Extension>
<Extension>.mat</Extension>
<Extension>.meta</Extension>
<Extension>.prefab</Extension>
<Extension>.unity</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Unix_Assembly</Name>
<Extensions>
<Extension>.s</Extension>
<Extension>.ms</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Vim_Snippet</Name>
<Extensions>
<Extension>.snip</Extension>
<Extension>.snippet</Extension>
<Extension>.snippets</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Vim_script</Name>
<Extensions>
<Extension>.vim</Extension>
<Extension>.vba</Extension>
<Extension>.vmb</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Visual_Basic_.NET</Name>
<Extensions>
<Extension>.vb</Extension>
<Extension>.vbhtml</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Wavefront_Material</Name>
<Extensions>
<Extension>.mtl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Wavefront_Object</Name>
<Extensions>
<Extension>.obj</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Web_Ontology_Language</Name>
<Extensions>
<Extension>.owl</Extension>
</Extensions>
</Technology>
<Technology>
<Name>Wget_Config</Name>
<Extensions />
</Technology>
<Technology>
<Name>Windows_Registry_Entries</Name>
<Extensions>
<Extension>.reg</Extension>
</Extensions>
</Technology>
<Technology>
<Name>World_of_Warcraft_Addon_Data</Name>
<Extensions>
<Extension>.toc</Extension>
</Extensions>
</Technology>
<Technology>
<Name>X_BitMap</Name>
<Extensions>
<Extension>.xbm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>X_Font_Directory_Index</Name>
<Extensions />
</Technology>
<Technology>
<Name>X_PixMap</Name>
<Extensions>
<Extension>.xpm</Extension>
<Extension>.pm</Extension>
</Extensions>
</Technology>
<Technology>
<Name>XML_Property_List</Name>
<Extensions>
<Extension>.plist</Extension>
<Extension>.stTheme</Extension>
<Extension>.tmCommand</Extension>
<Extension>.tmLanguage</Extension>
<Extension>.tmPreferences</Extension>
<Extension>.tmSnippet</Extension>
<Extension>.tmTheme</Extension>
</Extensions>
</Technology>
<Technology>
<Name>cURL_Config</Name>
<Extensions />
</Technology>
<Technology>
<Name>mIRC_Script</Name>
<Extensions>
<Extension>.mrc</Extension>
</Extensions>
</Technology>
</ArrayOfTechnologies>"
                          );
            }


        }
    }
}
